//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursemanager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursemanagerEntities : DbContext
    {
        public CoursemanagerEntities()
            : base("name=CoursemanagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        public DbSet<Classse> Classse { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Stutents> Stutents { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseManagement> CourseManagements { get; set; }
        public DbSet<ActionLink> ActionLink { get; set; }
        public DbSet<Sidebar> Sidebar { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
