// <auto-generated />
namespace Coursemanager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class actionlink1912042026 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actionlink1912042026));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041229324_actionlink1912042026"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
