// <auto-generated />
namespace Coursemanager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class creat201912161951 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creat201912161951));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161151107_creat201912161951"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
