// <auto-generated />
namespace Coursemanager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create20191127 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create20191127));
        
        string IMigrationMetadata.Id
        {
            get { return "201911270901598_Create20191127"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
